version: '3.8'

services:
  remote-click-api:
    build:
      context: ./api
    restart: unless-stopped
    ports:
      # Exposes the API on port 5000 of your server.
      # You can change the left-side number if port 5000 is taken.
      # Format: <HOST_PORT>:<CONTAINER_PORT>
      - "5000:5000"
    container_name: remote-click-api
    networks:
      - remote-click-net

networks:
  remote-click-net:
    driver: bridge
